# Server options
server.port=8080
server.servlet.context-path=/

# Endpoints to rule engine
app.brms.calculocotacao=http://brms-rules-globalvida-cotacao/rest/regracalculocotacao
app.brms.calculoassistencia=http://brms-rules-globalvida-cotacao/rest/regracalculoassistencia
app.brms.regraaceitacao=http://brms-rules-globalvida-cotacao/rest/regraaceitacao
app.brms.calculoreverso=http://brms-rules-globalvida-cotacao/rest/regracalculoreverso

## Handler to aws resources
#spring.config.import=optional:aws-secretsmanager:/secret/brms-rules-dev
#
## Database config
#spring.datasource.url=jdbc:postgresql://${URL_endpoint}:5432/DBR
#spring.datasource.username=${user}
#spring.datasource.password=${password}
#spring.datasource.driver-class-name=org.postgresql.Driver

# Disable all database related configurations
spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
