# Server options
server.port=8080
server.servlet.context-path=/

# Endpoints to rule engine
app.brms.calculocotacao=${calculocotacao}
app.brms.calculoassistencia=${calculoassistencia}
app.brms.regraaceitacao=${regraaceitacao}
app.brms.calculoreverso=${calculoreverso}

## Handler to aws resources
#spring.config.import=optional:aws-secretsmanager:/secret/brms-rules-dev
#
## Database config
#spring.datasource.url=jdbc:postgresql://${URL_endpoint}:5432/DBR
#spring.datasource.username=${user}
#spring.datasource.password=${password}
#spring.datasource.driver-class-name=org.postgresql.Driver

# Disable all database related configurations
spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
